### ISSUE TITLE
Warnings generated by MapperFactory 

### ISSUE THREAD

**Issue by MassiAtZend** [fabiopellati/apigility-tools#1]
The class 'MapperFactory' generates many warnings when 'disabled-mapper-listeners' is configured to an array because of the call to '$container->has($value)' on line 91.
The container abstract that implement the call cannot receive an array (only int or string).
A safe patch would be to add 'is_string($value)' in the condition 'if' condition before the call to '$container->get($value)' as follow:
Line 91: if (is_string($value) and $container->has($value)) {

PS: I know I needed to create a PR, but this is too simple to waste time on a PR.

**Comment by fabiopellati** [comment]
it's an old configuration file.
not an issue.
